[project]
name = "praktykiprogcicd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "pylint>=3.3.7",
    "pytest>=8.4.0",
    "ruff>=0.11.13",
]
