name: Python application
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with Pytest
        run: |
          pytest
      - name: Lint with Pylint
        run: |
          pylint ./utils.py
      - name: Lint with Ruff
        run: |
          ruff check utils.py
      - name: Format with Ruff
        run: |
          ruff format .
      - name: Format with Black
        run: |
          black .
